Update dashbot-lib.js
sinned/natoAlphabet-bixby pull request #2
Opened 2019-11-03 10:47 UTC by error404notfound

Updating to bixbyUserId removing the depreciated userId

2019-11-04 20:11 UTC, rogerkibbe commented
Need to add permissions for bixbyUserID for this to work e.g. need to add the following to capsule.bxb
```
permissions {
  bixby-user-id-access
}
```

2019-11-04 20:12 UTC, rogerkibbe requested changes
Need to add permissions for bixbyUserId e.g. add the following to capsule.bxb
```
permissions {
  bixby-user-id-access
}
```

2019-11-05 09:13 UTC, error404notfound commented
Updated. to include permissions ;)

2019-11-18 21:08 UTC, sinned approved these changes

2019-11-18 21:10 UTC, merged